## **Как загрузить данные в Google Colab?**

1. Из Github (файлы <25 МБ)
2. С локального диска
3. С Google Диска

In [4]:
# Github
# 1. Нажмите на файл с данными, которые хотите подключить
# 2. Нажмите "Raw"
# 3. Скопируйте ссылку открывшейся старницы
import pandas as pd
import numpy as np

url1 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/X_train.csv'
url2 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/studs_info.csv'
url3 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/zachety.csv'
url4 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/y_train.csv'

x_train = pd.read_csv(url1)
studs_info = pd.read_csv(url2)
zachety = pd.read_csv(url3)
y_train = pd.read_csv(url4)

## Вариант 2.

Кто делает:
1. Ивлиев Степан Дмитриевич
2. Игнатов Игорь Дмитриевич
3. Казанов Амир Ринатович
4. Клячин Иван Николаевич
5. Котов Александр Андреевич
6. Мелешкин Кирилл Андреевич
7. Файзуллин Илья Денисович
8. Чупрова Ася Александровна

1. Посмотреть размерность дата фреймов.
2. Соедить два датафрейма X_train и y_train в один train по индексам.
3. Посчитать пропуски в датафрейме studs_info.
4. Посчитать сколько мужчин, сколько женщин в датафрейме studs_info.
5. Создать новый датафрейм из studs_info, в котором будут только мужчины 2019-06-30 года выпуска.
6. Разложить колонку "Дата выдачи" на четыре: Год выдачи, Месяц выдачи, День выдачи, Время выдачи.
7. Посчитать сколько уникальных значений в колонке studs_info['Статус'] и сколько раз каждое значение встречается в датафрейм.
8. Посчитать сколько раз какая оценка встречатся в датафрейм y_train.
9. Посчитать средний балл для студента с ID=175711 по всем предметам.
10. Удалить любую ненужны колонку на ваш вгляд из датафрейм train.

In [10]:
print (f'X_train: \nСтрок: {x_train.shape[0]}\nСтолбцов: {x_train.shape[1]}\n')
print (f'Studs_info: \nСтрок: {studs_info.shape[0]}\nСтолбцов: {studs_info.shape[1]}\n')
print (f'Zachety: \nСтрок: {zachety.shape[0]}\nСтолбцов: {zachety.shape[1]}\n')
print (f'Y_train: \nСтрок: {y_train.shape[0]}\nСтолбцов: {y_train.shape[1]}\n')

X_train:
Строк: 105058
Столбцов: 8

Studs_info:
Строк: 5466
Столбцов: 13

Zachety:
Строк: 133223
Столбцов: 8

Y_train:
Строк: 105058
Столбцов: 2

In [126]:
train = pd.concat([x_train, y_train], axis = 1)
train.drop(columns = 'Unnamed: 0', inplace = True)
train.head(10)

,STD_ID,НАПРАВЛЕНИЕ,ГОД,КУРС,СЕМЕСТР,АТТЕСТАЦИЯ,ДИСЦИПЛИНА,index,mark
0,175711,38.03.02 Менеджмент,2018-2019,2.0,4.0,Экзамен,Маркетинг,51081,5
1,100647,31.05.01 Лечебное дело,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг...",72921,5
2,199311,31.05.03 Стоматология,2019-2020,1.0,1.0,Экзамен,Химия,96438,5
3,162002,38.03.02 Менеджмент,2017-2018,2.0,3.0,Экзамен,Статистика,273044,4
4,108384,31.05.01 Лечебное дело,2018-2019,5.0,9.0,Экзамен,Педиатрия,371309,3
5,173641,15.03.05 Конструкторско-технологическое обеспе...,2017-2018,1.0,2.0,Экзамен,Теоретическая механика,40650,5
6,193764,08.03.01 Строительство,2018-2019,1.0,2.0,Курсовая работа,Основы архитектуры и строительных конструкций,192280,5
7,182383,11.03.03 Конструирование и технология электрон...,2017-2018,1.0,2.0,Дифференцированный зачет,История,245859,4
8,142736,35.03.04 Агрономия,2018-2019,4.0,7.0,Экзамен,Технические культуры,4110,5
9,151477,31.05.01 Лечебное дело,2015-2016,1.0,1.0,Дифференцированный зачет,Практика учебная : уход за больными терапевтич...,44829,4

In [37]:
print("Количество пропусков:", studs_info.isna().sum().sum())
#studs_info.head()

Количество пропусков: 5822

In [49]:
t = studs_info['Пол'].value_counts()
print(f'Мужчин: {t[1]}\nЖенщин: {t[0]}')
#studs_info.head()

Мужчин: 2273
Женщин: 3192

In [134]:
stinfo = studs_info[studs_info['Пол'] == 'М']
stinfo = stinfo[stinfo['Дата выпуска'] == '2019-06-30']
stinfo.head()

,STD_ID,number,Пол,Статус,Дата выпуска,Категория обучения,Форма обучения,Шифр,направление (специальность),,Образование,Дата выдачи,Что именно закончил
41,141750,13098.0,М,ВЫП,2019-06-30,БП,Д,38.03.01,Экономика,4214.0,СР,2015-06-26 00:00:00,"СРЕДНЯЯ ШКОЛА N 33, НОВГОРОД"
52,141829,12000.0,М,ВЫП,2019-06-30,БП,Д,11.03.01,Радиотехника,9921.0,СР,2015-06-26 00:00:00,"СРЕДНЯЯ ШКОЛА N 21, НОВГОРОД"
64,139074,12173.0,М,ВЫП,2019-06-30,БП,З,35.03.04,Агрономия,9971.0,СП,2015-01-30 00:00:00,"ГОУ НПО ""Агролицей №25"" , СТАРАЯ РУССА"
68,139056,12264.0,М,ВЫП,2019-06-30,БП,З,35.03.01,Лесное дело,8620.0,СР,2013-06-24 00:00:00,"МОУ СОШ N 1, СОЛЬЦЫ с филиалом в Куклино"
83,170352,11359.0,М,ВЫП,2019-06-30,ДОГ,З,08.03.01,Строительство,4661.0,СП,2015-07-01 00:00:00,ТЕХНИКУМ ДРУГОЙ

In [133]:
date = studs_info['Дата выдачи'].str.split(' ', expand = True)
date_final = pd.concat([date[0].str.split('-', expand = True), date[1]], axis = 1)
date_final.columns = ['Год выдачи', 'Месяц выдачи', 'День выдачи', 'Время выдачи']
studs_info_new = pd.concat([studs_info, date_final], axis = 1).drop('Дата выдачи', axis = 1)
studs_info_new.head()

,STD_ID,number,Пол,Статус,Дата выпуска,Категория обучения,Форма обучения,Шифр,направление (специальность),,Образование,Что именно закончил,Год выдачи,Месяц выдачи,День выдачи,Время выдачи
0,99136,13951.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2629.0,СР,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,2013,06,26,00:00:00
1,99112,13998.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,8240.0,СР,"МОУ СОШ N 2, ПЕСТОВО",2012,06,23,00:00:00
2,99109,13999.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2314.0,СР,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,2013,06,25,00:00:00
3,99125,13953.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2345.0,СР,"Гимназия ""ГАРМОНИЯ""",2013,06,23,00:00:00
4,100676,13950.0,М,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2650.0,СР,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,2012,06,29,00:00:00

In [132]:
print(studs_info['Статус'].unique(), '\n')
print(studs_info['Статус'].value_counts())

['ВЫП' 'СТ' nan]

СТ     5001
ВЫП     464
Name: Статус, dtype: int64

In [114]:
y_train['mark'].value_counts()

4    42217
5    41085
3    21756
Name: mark, dtype: int64

In [131]:
av = train[train['STD_ID'] == 175711]['mark'].sum() / train[train['STD_ID'] == 175711].shape[0]
av

4.181818181818182

In [128]:
train.drop('АТТЕСТАЦИЯ', axis = 1).head(10)

,STD_ID,НАПРАВЛЕНИЕ,ГОД,КУРС,СЕМЕСТР,ДИСЦИПЛИНА,index,mark
0,175711,38.03.02 Менеджмент,2018-2019,2.0,4.0,Маркетинг,51081,5
1,100647,31.05.01 Лечебное дело,2015-2016,3.0,5.0,"Пропедевтика внутренних болезней, лучевая диаг...",72921,5
2,199311,31.05.03 Стоматология,2019-2020,1.0,1.0,Химия,96438,5
3,162002,38.03.02 Менеджмент,2017-2018,2.0,3.0,Статистика,273044,4
4,108384,31.05.01 Лечебное дело,2018-2019,5.0,9.0,Педиатрия,371309,3
5,173641,15.03.05 Конструкторско-технологическое обеспе...,2017-2018,1.0,2.0,Теоретическая механика,40650,5
6,193764,08.03.01 Строительство,2018-2019,1.0,2.0,Основы архитектуры и строительных конструкций,192280,5
7,182383,11.03.03 Конструирование и технология электрон...,2017-2018,1.0,2.0,История,245859,4
8,142736,35.03.04 Агрономия,2018-2019,4.0,7.0,Технические культуры,4110,5
9,151477,31.05.01 Лечебное дело,2015-2016,1.0,1.0,Практика учебная : уход за больными терапевтич...,44829,4