# Домашнее задание

В домашнем задании вам необходимо рассмтреть данные с олимпиады НТИ по профилю "Исскусственный интеллект" за 2019-2020 год.

Задачу можно найти по ссылке:

https://www.kaggle.com/c/onti-students-performance/data

## **Как загрузить данные в Google Colab?**

1. Из Github (файлы <25 МБ)
2. С локального диска
3. С Google Диска

In [177]:
# Github
# 1. Нажмите на файл с данными, которые хотите подключить
# 2. Нажмите "Raw"
# 3. Скопируйте ссылку открывшейся старницы
import pandas as pd

url1 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/X_train.csv'
url2 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/studs_info.csv'
url3 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/zachety.csv'
url4 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/y_train.csv'

X_train = pd.read_csv(url1)
studs_info = pd.read_csv(url2)
zachety = pd.read_csv(url3)
y_train = pd.read_csv(url4)
print(studs_info)

      STD_ID     number Пол Статус Дата выпуска Категория обучения  \
0      99136    13951.0   Ж    ВЫП   2019-08-31                 БП
1      99112    13998.0   Ж    ВЫП   2019-08-31                 БП
2      99109    13999.0   Ж    ВЫП   2019-08-31                 БП
3      99125    13953.0   Ж    ВЫП   2019-08-31                 БП
4     100676    13950.0   М    ВЫП   2019-08-31                 БП
...      ...        ...  ..    ...          ...                ...
5461  100678      978.0   Ж     СТ          NaN                 БП
5462  100663     1021.0   Ж     СТ          NaN                ДОГ
5463  191630     6447.0   Ж     СТ          NaN                ДОГ
5464  191625     3765.0   Ж     СТ          NaN                ДОГ
5465  194978     5245.0   Ж     СТ          NaN                ДОГ

     Форма обучения      Шифр направление (специальность)         Образование  \
0                 Д  31.05.01               Лечебное дело  2629.0          СР
1                 Д  31.05.01               Лечебное дело  8240.0          СР
2                 Д  31.05.01               Лечебное дело  2314.0          СР
3                 Д  31.05.01               Лечебное дело  2345.0          СР
4                 Д  31.05.01               Лечебное дело  2650.0          СР
...             ...       ...                         ...     ...         ...
5461              Д  31.05.01               Лечебное дело  2388.0          СР
5462              Д  31.05.01               Лечебное дело  2554.0          СР
5463              Д  31.05.01               Лечебное дело  6692.0          СР
5464              Д  31.05.01               Лечебное дело     NaN         NaN
5465              Д  31.05.01               Лечебное дело     NaN         NaN

              Дата выдачи        Что именно закончил
0     2013-06-26 00:00:00  ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
1     2012-06-23 00:00:00     МОУ СОШ N   2, ПЕСТОВО
2     2013-06-25 00:00:00  ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
3     2013-06-23 00:00:00        Гимназия "ГАРМОНИЯ"
4     2012-06-29 00:00:00  ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
...                   ...                        ...
5461  2013-06-21 00:00:00  ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
5462  2013-06-27 00:00:00  ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
5463  2014-05-31 00:00:00  ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
5464                  NaN                        NaN
5465                  NaN                        NaN

[5466 rows x 13 columns]

## Вариант 1.

Кто делает:
1. Александров Данила Александрович
2. Быков Дмитрий Александрович 
3. Горбунов Сергей Михайлович 
4. Горячко Дарья Романовна 
5. Громов Алексей Игоревич
6. Игнатов Константин Дмитриевич
7. Ямпольская Ирина Вадимовна
8. Дидковский Илья Радионович

1. Посмотреть размерность дата фреймов.
2. Соедить два датафрейма X_train и y_train в один train по индексам.
3. Посчитать пропуски в получившемся датафрейме train.
4. Посчитать сколько раз встречается каждая специальность в колонке studs_info['направление (специальность)'].
5. Создать новый датафрейм из studs_info, в котором будут только женщины с лечебного дела.
6. Разложить колонку "Дата выпуска" на три: Год выпуска, Месяц выпуска, День выпуска.
7. Посчитать сколько уникальных значений в колонке studs_info['Категория обучения'].
8. Заменить в колонке studs_info['Категория обучения'] все строковые категории на числовые.
9. Удалить ненужную на ваш вгляд колонку из датафрейма studs_info.
10. Посчитать сколько мужчин выпустились 2019-08-31.

# 1. Посмотреть размерность дата фреймов:

In [187]:
# 1. Посмотреть размерность дата фреймов:
raz_X_train=X_train.shape
raz_studs_info=studs_info.shape
raz_zachety=zachety.shape
raz_y_train=y_train.shape
print(X_train.shape)
print(raz_studs_info)
print(raz_zachety)
print(raz_y_train)

(105058, 8)
(5466, 13)
(133223, 8)
(105058, 2)

# 2. Соедить два датафрейма X_train и y_train в один train по индексам.

In [186]:
# 2. Соедить два датафрейма X_train и y_train в один train по индексам.
train=pd.concat([X_train, y_train], axis=1)
train

,Unnamed: 0,STD_ID,НАПРАВЛЕНИЕ,ГОД,КУРС,СЕМЕСТР,АТТЕСТАЦИЯ,ДИСЦИПЛИНА,index,mark
0,51081,175711,38.03.02 Менеджмент,2018-2019,2.0,4.0,Экзамен,Маркетинг,51081,5
1,72921,100647,31.05.01 Лечебное дело,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг...",72921,5
2,96438,199311,31.05.03 Стоматология,2019-2020,1.0,1.0,Экзамен,Химия,96438,5
3,273044,162002,38.03.02 Менеджмент,2017-2018,2.0,3.0,Экзамен,Статистика,273044,4
4,371309,108384,31.05.01 Лечебное дело,2018-2019,5.0,9.0,Экзамен,Педиатрия,371309,3
...,...,...,...,...,...,...,...,...,...,...
105053,224856,176141,40.03.01 Юриспруденция,2017-2018,1.0,2.0,Курсовая работа,Конституционное право,224856,3
105054,260998,182794,31.05.01 Лечебное дело,2018-2019,2.0,4.0,Экзамен,Нормальная физиология,260998,3
105055,57245,162391,31.05.01 Лечебное дело,2016-2017,1.0,2.0,Дифференцированный зачет,Иностранный язык,57245,4
105056,218529,202479,38.03.01 Экономика,2017-2018,1.0,1.0,Дифференцированный зачет,Информатика,218529,4
105057,233318,182325,08.03.01 Строительство,2018-2019,2.0,3.0,Курсовая работа,Технологические процессы в строительстве,233318,4

3. Посчитать пропуски в получившемся датафрейме train.

In [184]:
# 3. Посчитать пропуски в получившемся датафрейме train.
prop=train.isna().sum()
prop

Unnamed: 0     0
STD_ID         0
НАПРАВЛЕНИЕ    0
ГОД            0
КУРС           0
СЕМЕСТР        0
АТТЕСТАЦИЯ     0
ДИСЦИПЛИНА     0
index          0
mark           0
dtype: int64

4. Посчитать сколько раз встречается каждая специальность в колонке studs_info['направление (специальность)'].

In [185]:
# 4. Посчитать сколько раз встречается каждая специальность в колонке studs_info['направление (специальность)'].
kolvo = train['НАПРАВЛЕНИЕ'].value_counts()
kolvo

31.05.01 Лечебное дело                                                                23378
31.05.03 Стоматология                                                                  7996
44.03.05 Педагогическое образование (с двумя профилями подготовки)                     7996
40.03.01 Юриспруденция                                                                 6036
38.03.01 Экономика                                                                     5192
08.03.01 Строительство                                                                 4213
44.03.01 Педагогическое образование                                                    3676
38.03.02 Менеджмент                                                                    3344
07.03.01 Архитектура                                                                   2893
45.03.02 Лингвистика                                                                   2741
33.05.01 Фармация                                                                      2721
07.03.03 Дизайн архитектурной среды                                                    2038
42.03.02 Журналистика                                                                  2028
13.03.01 Теплоэнергетика и теплотехника                                                1986
44.03.03 Специальное (дефектологическое) образование                                   1928
38.03.03 Управление персоналом                                                         1628
11.03.03 Конструирование и технология электронных средств                              1564
09.03.01 Информатика и вычислительная техника                                          1558
15.03.05 Конструкторско-технологическое обеспечение машиностроительных производств     1553
35.03.06 Агроинженерия                                                                 1468
54.03.01 Дизайн                                                                        1385
23.03.03 Эксплуатация транспортно-технологических машин и комплексов                   1382
04.05.01 Фундаментальная и прикладная химия                                            1322
21.03.02 Землеустройство и кадастры                                                    1252
45.03.01 Филология                                                                      946
37.03.01 Психология                                                                     932
35.03.07 Технология производства и переработки сельскохозяйственной продукции           928
35.03.01 Лесное дело                                                                    850
46.03.01 История                                                                        830
11.03.01 Радиотехника                                                                   790
29.03.04 Технология художественной обработки материалов                                 790
36.03.02 Зоотехния                                                                      744
06.03.01 Биология                                                                       665
05.03.06 Экология и природопользование                                                  636
38.03.04 Государственное и муниципальное управление                                     629
35.03.04 Агрономия                                                                      628
01.03.02 Прикладная математика и информатика                                            528
51.03.01 Культурология                                                                  515
44.03.02 Психолого-педагогическое образование                                           481
11.03.04 Электроника и наноэлектроника                                                  465
05.03.02 География                                                                      463
47.03.01 Философия                                                                      380
40.04.01 Юриспруденция                                                                  378
15.03.06 Мехатроника и робототехника                                                    277
34.03.01 Сестринское дело                                                               215
11.04.04 Электроника и наноэлектроника                                                  131
38.04.02 Менеджмент                                                                     106
11.04.03 Конструирование и технология электронных средств                                91
45.04.01 Филология                                                                       84
36.04.02 Зоотехния                                                                       78
01.04.02 Прикладная математика и информатика                                             63
15.04.05 Конструкторско-технологическое обеспечение машиностроительных производств       52
11.04.01 Радиотехника                                                                    48
08.04.01 Строительство                                                                   43
42.04.02 Журналистика                                                                    14
Name: НАПРАВЛЕНИЕ, dtype: int64

5. Создать новый датафрейм из studs_info, в котором будут только женщины с лечебного дела

In [183]:
# 5. Создать новый датафрейм из studs_info, в котором будут только женщины с лечебного дела.
new_frame = studs_info[studs_info['Пол']=='Ж']
otvet = new_frame[new_frame['направление (специальность)']=='Лечебное дело']
otvet

,STD_ID,number,Пол,Статус,Дата выпуска,Категория обучения,Форма обучения,Шифр,направление (специальность),,Образование,Дата выдачи,Что именно закончил
0,99136,13951.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2629.0,СР,2013-06-26 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
1,99112,13998.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,8240.0,СР,2012-06-23 00:00:00,"МОУ СОШ N 2, ПЕСТОВО"
2,99109,13999.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2314.0,СР,2013-06-25 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
3,99125,13953.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2345.0,СР,2013-06-23 00:00:00,"Гимназия ""ГАРМОНИЯ"""
5,99099,13959.0,Ж,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,8800.0,СР,2013-06-21 00:00:00,"МОУ СОШ (полная), ХОЛМ"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5461,100678,978.0,Ж,СТ,NaN,БП,Д,31.05.01,Лечебное дело,2388.0,СР,2013-06-21 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
5462,100663,1021.0,Ж,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,2554.0,СР,2013-06-27 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
5463,191630,6447.0,Ж,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,6692.0,СР,2014-05-31 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
5464,191625,3765.0,Ж,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaN,NaN
5465,194978,5245.0,Ж,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaN,NaN

6. Разложить колонку "Дата выпуска" на три: Год выпуска, Месяц выпуска, День выпуска.

In [182]:
# 6.Разложить колонку "Дата выпуска" на три: Год выпуска, Месяц выпуска, День выпуска.
#studs_info['Дата выпуска'].str.split('-')
new_studs_info = studs_info['Дата выпуска'].str.split('-',expand=True)
new_studs_info.columns=['Год выпуска','Месяц выпуска','День выпуска']
final = pd.concat([studs_info,new_studs_info],axis=1).drop('Дата выпуска',axis=1)
final

,STD_ID,number,Пол,Статус,Категория обучения,Форма обучения,Шифр,направление (специальность),,Образование,Дата выдачи,Что именно закончил,Год выпуска,Месяц выпуска,День выпуска
0,99136,13951.0,Ж,ВЫП,БП,Д,31.05.01,Лечебное дело,2629.0,СР,2013-06-26 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,2019,08,31
1,99112,13998.0,Ж,ВЫП,БП,Д,31.05.01,Лечебное дело,8240.0,СР,2012-06-23 00:00:00,"МОУ СОШ N 2, ПЕСТОВО",2019,08,31
2,99109,13999.0,Ж,ВЫП,БП,Д,31.05.01,Лечебное дело,2314.0,СР,2013-06-25 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,2019,08,31
3,99125,13953.0,Ж,ВЫП,БП,Д,31.05.01,Лечебное дело,2345.0,СР,2013-06-23 00:00:00,"Гимназия ""ГАРМОНИЯ""",2019,08,31
4,100676,13950.0,М,ВЫП,БП,Д,31.05.01,Лечебное дело,2650.0,СР,2012-06-29 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,2019,08,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5461,100678,978.0,Ж,СТ,БП,Д,31.05.01,Лечебное дело,2388.0,СР,2013-06-21 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,NaN,NaN,NaN
5462,100663,1021.0,Ж,СТ,ДОГ,Д,31.05.01,Лечебное дело,2554.0,СР,2013-06-27 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,NaN,NaN,NaN
5463,191630,6447.0,Ж,СТ,ДОГ,Д,31.05.01,Лечебное дело,6692.0,СР,2014-05-31 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА,NaN,NaN,NaN
5464,191625,3765.0,Ж,СТ,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5465,194978,5245.0,Ж,СТ,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaN,NaN,NaN,NaN,NaN

7. Посчитать сколько уникальных значений в колонке studs_info['Категория обучения'].

In [181]:
# 7. Посчитать сколько уникальных значений в колонке studs_info['Категория обучения'].
# какие ? - print(studs_info['Категория обучения'].unique())
print(len((studs_info['Категория обучения'].unique())))

3

8. Заменить в колонке studs_info['Категория обучения'] все строковые категории на числовые.

9. Удалить ненужную на ваш вгляд колонку из датафрейма studs_info.

In [179]:
# 9. Удалить ненужную на ваш вгляд колонку из датафрейма studs_info.
studs_info.drop(columns = ['Шифр'])

,STD_ID,number,Пол,Статус,Дата выпуска,Категория обучения,Форма обучения,направление (специальность),,Образование,Дата выдачи,Что именно закончил
0,99136,13951.0,Ж,ВЫП,2019-08-31,БП,Д,Лечебное дело,2629.0,СР,2013-06-26 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
1,99112,13998.0,Ж,ВЫП,2019-08-31,БП,Д,Лечебное дело,8240.0,СР,2012-06-23 00:00:00,"МОУ СОШ N 2, ПЕСТОВО"
2,99109,13999.0,Ж,ВЫП,2019-08-31,БП,Д,Лечебное дело,2314.0,СР,2013-06-25 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
3,99125,13953.0,Ж,ВЫП,2019-08-31,БП,Д,Лечебное дело,2345.0,СР,2013-06-23 00:00:00,"Гимназия ""ГАРМОНИЯ"""
4,100676,13950.0,М,ВЫП,2019-08-31,БП,Д,Лечебное дело,2650.0,СР,2012-06-29 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
...,...,...,...,...,...,...,...,...,...,...,...,...
5461,100678,978.0,Ж,СТ,NaN,БП,Д,Лечебное дело,2388.0,СР,2013-06-21 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
5462,100663,1021.0,Ж,СТ,NaN,ДОГ,Д,Лечебное дело,2554.0,СР,2013-06-27 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
5463,191630,6447.0,Ж,СТ,NaN,ДОГ,Д,Лечебное дело,6692.0,СР,2014-05-31 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
5464,191625,3765.0,Ж,СТ,NaN,ДОГ,Д,Лечебное дело,NaN,NaN,NaN,NaN
5465,194978,5245.0,Ж,СТ,NaN,ДОГ,Д,Лечебное дело,NaN,NaN,NaN,NaN

 10. Посчитать сколько мужчин выпустились 2019-08-31.

In [180]:
# 10. Посчитать сколько мужчин выпустились 2019-08-31.
new_frame = studs_info[studs_info['Пол']=='М']
otvet = new_frame[new_frame['Дата выпуска']=='2019-08-31']
print(otvet['Дата выпуска'].value_counts())

2019-08-31    81
Name: Дата выпуска, dtype: int64