# Домашнее задание

В домашнем задании вам необходимо рассмтреть данные с олимпиады НТИ по профилю "Исскусственный интеллект" за 2019-2020 год.

Задачу можно найти по ссылке:

https://www.kaggle.com/c/onti-students-performance/data

## **Как загрузить данные в Google Colab?**

1. Из Github (файлы <25 МБ)
2. С локального диска
3. С Google Диска

In [ ]:
# Github
# 1. Нажмите на файл с данными, которые хотите подключить
# 2. Нажмите "Raw"
# 3. Скопируйте ссылку открывшейся старницы
import pandas as pd

url1 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/X_train.csv'
url2 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/studs_info.csv'
url3 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/zachety.csv'
url4 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/y_train.csv'

X_train = pd.read_csv(url1)
studs_info = pd.read_csv(url2)
zachety = pd.read_csv(url3)
y_train = pd.read_csv(url4)

In [ ]:
# С локального компьютера

from google.colab import files
uploaded = files.upload()

In [ ]:
studs_info = pd.read_csv('studs_info.csv')
X_train = pd.read_csv('X_train.csv')
y_train = pd.read_csv('y_train.csv')
zachety = pd.read_csv('zachety.csv')

In [ ]:
# Google disk

from google.colab import drive
drive.mount('/content/drive')

In [ ]:
path = "copied path"
# /content/drive/MyDrive/Data Science для школьников/ОНТИ /ONTI Students performance/X_train.csv
df_bonus = pd.read_csv(path)

## Вариант 1.

Кто делает:
1. Александров Данила Александрович
2. Быков Дмитрий Александрович 
3. Горбунов Сергей Михайлович 
4. Горячко Дарья Романовна 
5. Громов Алексей Игоревич
6. Игнатов Константин Дмитриевич
7. Ямпольская Ирина Вадимовна
8. Дидковский Илья Радионович

1. Посмотреть размерность дата фреймов.
2. Соедить два датафрейма X_train и y_train в один train по индексам.
3. Посчитать пропуски в получившемся датафрейме train.
4. Посчитать сколько раз встречается каждая специальность в колонке studs_info['направление (специальность)'].
5. Создать новый датафрейм из studs_info, в котором будут только женщины с лечебного дела.
6. Разложить колонку "Дата выпуска" на три: Год выпуска, Месяц выпуска, День выпуска.
7. Посчитать сколько уникальных значений в колонке studs_info['Категория обучения'].
8. Заменить в колонке studs_info['Категория обучения'] все строковые категории на числовые.
9. Удалить ненужную на ваш вгляд колонку из датафрейма studs_info.
10. Посчитать сколько мужчин выпустились 2019-08-31.

## Вариант 2.

Кто делает:
1. Ивлиев Степан Дмитриевич
2. Игнатов Игорь Дмитриевич
3. Казанов Амир Ринатович
4. Клячин Иван Николаевич
5. Котов Александр Андреевич
6. Мелешкин Кирилл Андреевич
7. Файзуллин Илья Денисович
8. Чупрова Ася Александровна

1. Посмотреть размерность дата фреймов.
2. Соедить два датафрейма X_train и y_train в один train по индексам.
3. Посчитать пропуски в датафрейме studs_info.
4. Посчитать сколько мужчин, сколько женщин в датафрейме studs_info.
5. Создать новый датафрейм из studs_info, в котором будут только мужчины 2019-06-30 года выпуска.
6. Разложить колонку "Дата выдачи" на четыре: Год выдачи, Месяц выдачи, День выдачи, Время выдачи.
7. Посчитать сколько уникальных значений в колонке studs_info['Статус'] и сколько раз каждое значение встречается в датафрейм.
8. Посчитать сколько раз какая оценка встречатся в датафрейм y_train.
9. Посчитать средний балл для студента с ID=175711 по всем предметам.
10. Удалить любую ненужны колонку на ваш вгляд из датафрейм train.

In [ ]:
# Ваше решение

df[df['name'] == 'Ivan']

## Вариант 3.

Кто делает:
1. Морозов Максим Олегович
2. Переттруов Никита Артемович
3. Пославский Егор Константинович
4. Садохин Константин Павлович
5. Скиданов Дмитрий Артёмович
6. Судариков Андрей Геннадьевич
7. Таланов Максим Андреевич

Задания:
1. Посмотреть размерность дата фреймов.
2. Соедить два датафрейма X_train и y_train в один train по индексам.
3. Посчитать пропуски в датафрейме studs_info.
4. Посчитать сколько уникальных значений в колонке АТТЕСТАЦИЯ и сколько раз каждое из них встречается.
5. Переименовать все колонки датафрейм train, чтобы названия были маленькими буквами.
6. Разложить колонку "направление" на две: Код направления, Название направления.
7. Создать новый датафрейм, в котором будут только мужчины 3 курса обучения.
8. Заменить все строковые значения в колонке Пол на числовые.
9. Сколько всего студентов сдавали предмет "Информатика" в виде экзамена? И какой средний балл по всем сдававшим?

№1

In [13]:
# задание номер 1
import pandas as pd
url1 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/X_train.csv'
url2 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/studs_info.csv'
url3 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/zachety.csv'
url4 = 'https://raw.githubusercontent.com/Adelaaas/Data_science_basic_22-23_1/main/class_work_4_Pandas/ONTI%20Students%20performance/y_train.csv'

X_train = pd.read_csv(url1)
studs_info = pd.read_csv(url2)
zachety = pd.read_csv(url3)
y_train = pd.read_csv(url4)
print(X_train.shape)
print(studs_info.shape)
print(zachety.shape)
print(y_train.shape)

(105058, 8)
(5466, 13)
(133223, 8)
(105058, 2)

№2

In [14]:
final = pd.concat([y_train, X_train], axis=1)
final

,index,mark,Unnamed: 0,STD_ID,НАПРАВЛЕНИЕ,ГОД,КУРС,СЕМЕСТР,АТТЕСТАЦИЯ,ДИСЦИПЛИНА
0,51081,5,51081,175711,38.03.02 Менеджмент,2018-2019,2.0,4.0,Экзамен,Маркетинг
1,72921,5,72921,100647,31.05.01 Лечебное дело,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг..."
2,96438,5,96438,199311,31.05.03 Стоматология,2019-2020,1.0,1.0,Экзамен,Химия
3,273044,4,273044,162002,38.03.02 Менеджмент,2017-2018,2.0,3.0,Экзамен,Статистика
4,371309,3,371309,108384,31.05.01 Лечебное дело,2018-2019,5.0,9.0,Экзамен,Педиатрия
...,...,...,...,...,...,...,...,...,...,...
105053,224856,3,224856,176141,40.03.01 Юриспруденция,2017-2018,1.0,2.0,Курсовая работа,Конституционное право
105054,260998,3,260998,182794,31.05.01 Лечебное дело,2018-2019,2.0,4.0,Экзамен,Нормальная физиология
105055,57245,4,57245,162391,31.05.01 Лечебное дело,2016-2017,1.0,2.0,Дифференцированный зачет,Иностранный язык
105056,218529,4,218529,202479,38.03.01 Экономика,2017-2018,1.0,1.0,Дифференцированный зачет,Информатика
105057,233318,4,233318,182325,08.03.01 Строительство,2018-2019,2.0,3.0,Курсовая работа,Технологические процессы в строительстве

№3

In [15]:
studs_info.isna().sum()

STD_ID                            0
   number                         1
Пол                               1
Статус                            1
Дата выпуска                   5002
Категория обучения                1
Форма обучения                    1
Шифр                              1
направление (специальность)       1
                                191
Образование                     191
Дата выдачи                     240
Что именно закончил             191
dtype: int64

№4

In [19]:
final = pd.concat([y_train, X_train], axis=1)
x = len(final['АТТЕСТАЦИЯ'].unique())
print(final['АТТЕСТАЦИЯ'].value_counts())
print(x)

Экзамен                     60092
Дифференцированный зачет    37791
Курсовая работа              5522
Курсовой проект              1631
Зачет                          22
Name: АТТЕСТАЦИЯ, dtype: int64
5

№5

In [20]:
final = final.rename(columns={'НАПРАВЛЕНИЕ' : 'направление','ГОД' : 'год','КУРС' : 'курс','СЕМЕСТР' : 'семестр','АТТЕСТАЦИЯ' : 'аттестация','ДИСЦИПЛИНА' : 'дисциплина'})
final

,index,mark,Unnamed: 0,STD_ID,направление,год,курс,семестр,аттестация,дисциплина
0,51081,5,51081,175711,38.03.02 Менеджмент,2018-2019,2.0,4.0,Экзамен,Маркетинг
1,72921,5,72921,100647,31.05.01 Лечебное дело,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг..."
2,96438,5,96438,199311,31.05.03 Стоматология,2019-2020,1.0,1.0,Экзамен,Химия
3,273044,4,273044,162002,38.03.02 Менеджмент,2017-2018,2.0,3.0,Экзамен,Статистика
4,371309,3,371309,108384,31.05.01 Лечебное дело,2018-2019,5.0,9.0,Экзамен,Педиатрия
...,...,...,...,...,...,...,...,...,...,...
105053,224856,3,224856,176141,40.03.01 Юриспруденция,2017-2018,1.0,2.0,Курсовая работа,Конституционное право
105054,260998,3,260998,182794,31.05.01 Лечебное дело,2018-2019,2.0,4.0,Экзамен,Нормальная физиология
105055,57245,4,57245,162391,31.05.01 Лечебное дело,2016-2017,1.0,2.0,Дифференцированный зачет,Иностранный язык
105056,218529,4,218529,202479,38.03.01 Экономика,2017-2018,1.0,1.0,Дифференцированный зачет,Информатика
105057,233318,4,233318,182325,08.03.01 Строительство,2018-2019,2.0,3.0,Курсовая работа,Технологические процессы в строительстве

№6

In [21]:
new_df = final['направление'].str.split(" ", 1, expand=True)
new_df.columns=['Код навправления','Название направления']
final = pd.concat([new_df, final], axis=1)
final.drop(['направление'], axis=1, inplace=True)
final

,Код навправления,Название направления,index,mark,Unnamed: 0,STD_ID,год,курс,семестр,аттестация,дисциплина
0,38.03.02,Менеджмент,51081,5,51081,175711,2018-2019,2.0,4.0,Экзамен,Маркетинг
1,31.05.01,Лечебное дело,72921,5,72921,100647,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг..."
2,31.05.03,Стоматология,96438,5,96438,199311,2019-2020,1.0,1.0,Экзамен,Химия
3,38.03.02,Менеджмент,273044,4,273044,162002,2017-2018,2.0,3.0,Экзамен,Статистика
4,31.05.01,Лечебное дело,371309,3,371309,108384,2018-2019,5.0,9.0,Экзамен,Педиатрия
...,...,...,...,...,...,...,...,...,...,...,...
105053,40.03.01,Юриспруденция,224856,3,224856,176141,2017-2018,1.0,2.0,Курсовая работа,Конституционное право
105054,31.05.01,Лечебное дело,260998,3,260998,182794,2018-2019,2.0,4.0,Экзамен,Нормальная физиология
105055,31.05.01,Лечебное дело,57245,4,57245,162391,2016-2017,1.0,2.0,Дифференцированный зачет,Иностранный язык
105056,38.03.01,Экономика,218529,4,218529,202479,2017-2018,1.0,1.0,Дифференцированный зачет,Информатика
105057,08.03.01,Строительство,233318,4,233318,182325,2018-2019,2.0,3.0,Курсовая работа,Технологические процессы в строительстве

№7

In [10]:
male = studs_info[studs_info['Пол'] == "М"]
id = male['STD_ID'].values
zxc = final.loc[~final['STD_ID'].isin(id)]
finm = zxc[zxc['курс'] == 3.0]
finm

,Код навправления,Название направления,index,mark,Unnamed: 0,STD_ID,год,курс,семестр,аттестация,дисциплина
1,31.05.01,Лечебное дело,72921,5,72921,100647,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг..."
25,31.05.01,Лечебное дело,377876,5,377876,120764,2016-2017,3.0,5.0,Экзамен,"Общая хирургия, лучевая диагностика: общая хир..."
26,40.03.01,Юриспруденция,262326,5,262326,182155,2019-2020,3.0,5.0,Экзамен,Процессуальные особенности рассмотрения и разр...
27,44.03.01,Педагогическое образование,265821,5,265821,170624,2018-2019,3.0,6.0,Экзамен,Методика обучения русскому языку и литературе
29,40.03.01,Юриспруденция,302859,4,302859,165218,2018-2019,3.0,5.0,Курсовая работа,Уголовный процесс
...,...,...,...,...,...,...,...,...,...,...,...
104999,31.05.01,Лечебное дело,74999,3,74999,178356,2015-2016,3.0,6.0,Экзамен,Фармакология
105012,40.03.01,Юриспруденция,332062,4,332062,120898,2017-2018,3.0,5.0,Курсовая работа,Уголовный процесс
105014,44.03.03,Специальное (дефектологическое) образование,210503,4,210503,182260,2019-2020,3.0,5.0,Экзамен,Образование лиц с нарушениями интеллекта: дошк...
105021,31.05.03,Стоматология,317607,5,317607,165320,2018-2019,3.0,6.0,Дифференцированный зачет,"Практика производственная клиническая, в том ч..."
105050,07.03.01,Архитектура,73409,4,73409,96954,2016-2017,3.0,6.0,Экзамен,Архитектурное проектирование: архитектурное пр...

№8

In [26]:
mapping = {'М': 0, 'Ж': 1}
studs_info.replace({'Пол': mapping})

,STD_ID,number,Пол,Статус,Дата выпуска,Категория обучения,Форма обучения,Шифр,направление (специальность),,Образование,Дата выдачи,Что именно закончил
0,99136,13951.0,1.0,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2629.0,СР,2013-06-26 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
1,99112,13998.0,1.0,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,8240.0,СР,2012-06-23 00:00:00,"МОУ СОШ N 2, ПЕСТОВО"
2,99109,13999.0,1.0,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2314.0,СР,2013-06-25 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
3,99125,13953.0,1.0,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2345.0,СР,2013-06-23 00:00:00,"Гимназия ""ГАРМОНИЯ"""
4,100676,13950.0,0.0,ВЫП,2019-08-31,БП,Д,31.05.01,Лечебное дело,2650.0,СР,2012-06-29 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5461,100678,978.0,1.0,СТ,NaN,БП,Д,31.05.01,Лечебное дело,2388.0,СР,2013-06-21 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
5462,100663,1021.0,1.0,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,2554.0,СР,2013-06-27 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
5463,191630,6447.0,1.0,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,6692.0,СР,2014-05-31 00:00:00,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
5464,191625,3765.0,1.0,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaN,NaN
5465,194978,5245.0,1.0,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaN,NaN

№9

In [54]:
y = final[final['аттестация'] == 'Экзамен']
y = y[y['дисциплина'] == 'Информатика']
z = y.shape[0]
mark = y['mark'].sum() / z
print(z, mark)

60 4.6