In [1]:
!pip install opendatasets
import opendatasets as od
import pandas as pd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Requirement already satisfied: click in /usr/local/lib/python3.9/dist-packages (from opendatasets) (8.1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages (from opendatasets) (4.65.0)
Requirement already satisfied: kaggle in /usr/local/lib/python3.9/dist-packages (from opendatasets) (1.5.13)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (2.27.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (8.0.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (2022.12.7)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (1.26.15)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (1.16.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.9/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->kaggle->opendatasets) (3.4)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests->kaggle->opendatasets) (2.0.12)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [2]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import numpy as np
import pandas as pd

In [3]:
od.download("https://www.kaggle.com/competitions/laptop-price-prediction-misis/")

Downloading laptop-price-prediction-misis.zip to ./laptop-price-prediction-misis

100%|██████████| 29.1k/29.1k [00:00<00:00, 14.5MB/s]

Extracting archive ./laptop-price-prediction-misis/laptop-price-prediction-misis.zip to ./laptop-price-prediction-misis

In [267]:
train= pd.read_csv("/content/laptop-price-prediction-misis/Price_euros_train.csv")
train

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
1,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
2,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
3,6,Acer,Aspire 3,Notebook,15.6,1366x768,AMD A9-Series 9420 3GHz,4GB,500GB HDD,AMD Radeon R5,Windows 10,2.1kg,400.00
4,7,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.2GHz,16GB,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04kg,2139.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1103,1315,Asus,X556UJ-XO044T (i7-6500U/4GB/500GB/GeForce,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,4GB,500GB HDD,Nvidia GeForce 920M,Windows 10,2.2kg,720.32
1104,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00
1105,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00
1106,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00
1107,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00

In [268]:
train=train.drop(['laptop_ID'],axis=1)

In [188]:
train

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,1.34,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,898.94
1,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,1.83,512GB SSD,AMD Radeon Pro 455,macOS,1.83,2537.45
2,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,1.37,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,1803.60
3,Acer,Aspire 3,Notebook,15.6,1366x768,AMD A9-Series 9420 3GHz,2.10,500GB HDD,AMD Radeon R5,Windows 10,2.1,400.00
4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.2GHz,2.04,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04,2139.97
...,...,...,...,...,...,...,...,...,...,...,...,...
1103,Asus,X556UJ-XO044T (i7-6500U/4GB/500GB/GeForce,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,2.20,500GB HDD,Nvidia GeForce 920M,Windows 10,2.2,720.32
1104,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,1.80,128GB SSD,Intel HD Graphics 520,Windows 10,1.8,638.00
1105,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,1.50,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5,229.00
1106,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,2.19,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19,764.00
1107,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2.20,500GB HDD,Intel HD Graphics,Windows 10,2.2,369.00

In [269]:
train['Weight'] = train['Weight'].fillna("2.2kg")

In [270]:

train['ScreenResolution'] = train['ScreenResolution'].fillna("Full HD 1920x1080")

In [271]:
train['OpSys'] = train['OpSys'].fillna("Windows 10")

In [272]:

for i in range(0,1108):
  train['Ram'][i]=train['Ram'][i][-3::-1]
  train['Ram'][i]=train['Ram'][i][::-1]
train['Ram']=pd.to_numeric(train['Ram'])

<ipython-input-272-841c181eb1c8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['Ram'][i]=train['Ram'][i][-3::-1]
<ipython-input-272-841c181eb1c8>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['Ram'][i]=train['Ram'][i][::-1]

In [273]:
for i in range(0,1108):
  train['Weight'][i]=train['Weight'][i][-3::-1]
  train['Weight'][i]=train['Weight'][i][::-1]
train['Weight']=pd.to_numeric(train['Weight'])

<ipython-input-273-6804783ab8ba>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['Weight'][i]=train['Weight'][i][-3::-1]
<ipython-input-273-6804783ab8ba>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['Weight'][i]=train['Weight'][i][::-1]

In [287]:
train

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,269,4,13.3,1,60,8,2,49,8,1.34,898.94
1,1,268,4,15.4,11,81,16,29,8,8,1.83,2537.45
2,1,268,4,13.3,9,64,8,16,57,8,1.37,1803.60
3,0,51,3,15.6,0,14,4,26,16,5,2.10,400.00
4,1,268,4,15.4,11,80,16,15,58,3,2.04,2139.97
...,...,...,...,...,...,...,...,...,...,...,...,...
1103,2,505,3,15.6,0,85,4,26,63,5,2.20,720.32
1104,9,514,0,14.0,3,85,4,4,45,5,1.80,638.00
1105,9,176,3,14.0,0,33,2,33,38,5,1.50,229.00
1106,7,2,3,15.6,0,85,6,10,19,5,2.19,764.00
1107,2,503,3,15.6,0,33,4,26,38,5,2.20,369.00

In [190]:
train.isna().sum()

Company              0
Product              0
TypeName             0
Inches               0
ScreenResolution    11
Cpu                  0
Ram                  0
Memory               0
Gpu                  0
OpSys               53
Weight               0
Price_euros          0
dtype: int64

In [202]:
train["OpSys"].value_counts()

Windows 10      864
No OS            55
Linux            53
Windows 7        35
Chrome OS        25
macOS             8
Mac OS X          7
Windows 10 S      6
Android           2
Name: OpSys, dtype: int64

In [ ]:

fl=0
for i in range(0,1108):
  l=len(train['ScreenResolution'][i])
  fl=0
  for j in range(0,l):
    if((train['ScreenResolution'][i][j]=='1' or  train['ScreenResolution'][i][j]=='2' or train['ScreenResolution'][i][j]=='3') and fl==0):
      fl=1
      train['ScreenResolution'][i]=train['ScreenResolution'][i][j::]
      break
  print(train['ScreenResolution'][i])

In [229]:
a="qwertyuiop"
print(a[6::])

uiop

In [220]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1108 entries, 0 to 1107
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1108 non-null   object
 1   Product           1108 non-null   object
 2   TypeName          1108 non-null   object
 3   Inches            1108 non-null   float64
 4   ScreenResolution  1108 non-null   object
 5   Cpu               1108 non-null   object
 6   Ram               1108 non-null   int64
 7   Memory            1108 non-null   object
 8   Gpu               1108 non-null   object
 9   OpSys             1108 non-null   object
 10  Weight            1108 non-null   float64
 11  Price_euros       1108 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 104.0+ KB

In [277]:

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['Company']) 
train['Company'] = label_encoder.transform(train['Company'])

In [278]:
label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['Product']) 
train['Product'] = label_encoder.transform(train['Product'])

In [280]:
label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['TypeName']) 
train['TypeName'] = label_encoder.transform(train['TypeName'])

In [281]:
label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['Cpu']) 
train['Cpu'] = label_encoder.transform(train['Cpu'])

In [282]:
label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['Memory']) 
train['Memory'] = label_encoder.transform(train['Memory'])

In [109]:
label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['Ram']) 
train['Ram'] = label_encoder.transform(train['Ram'])

In [283]:
label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['Gpu']) 
train['Gpu'] = label_encoder.transform(train['Gpu'])

In [284]:
label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['OpSys']) 
train['OpSys'] = label_encoder.transform(train['OpSys'])

In [286]:
label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['ScreenResolution']) 
train['ScreenResolution'] = label_encoder.transform(train['ScreenResolution'])

In [113]:
label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['Weight']) 
train['Weight'] = label_encoder.transform(train['Weight'])

In [114]:
y=train["Price_euros"]
y

0        898.94
1       2537.45
2       1803.60
3        400.00
4       2139.97
         ...
1103     720.32
1104     638.00
1105     229.00
1106     764.00
1107     369.00
Name: Price_euros, Length: 1108, dtype: float64

In [101]:
x=train.drop(["Price_euros"],axis=1)
x

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
0,1,269,4,13.3,1,60,8,2,49,8,34
1,1,268,4,15.4,24,81,1,29,8,8,68
2,1,268,4,13.3,22,64,8,16,57,8,37
3,0,51,3,15.6,0,14,5,26,16,5,102
4,1,268,4,15.4,24,80,1,15,58,3,87
...,...,...,...,...,...,...,...,...,...,...,...
1103,2,505,3,15.6,0,85,5,26,63,5,110
1104,9,514,0,14.0,13,85,5,4,45,5,75
1105,9,176,3,14.0,0,33,3,33,38,5,54
1106,7,2,3,15.6,0,85,7,10,19,5,101
1107,2,503,3,15.6,0,33,5,26,38,5,110

In [ ]:


from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [ ]:
for i in range(0,1108):
  print(train['Ram'][i])

In [136]:
a="61GB"
a=a[-3::-1]
print(type(a))
a=int(a)
print(type(a))
a

<class 'str'>
<class 'int'>

16

In [7]:
train.isna().sum()

laptop_ID            0
Company              0
Product              0
TypeName             0
Inches               0
ScreenResolution    11
Cpu                  0
Ram                  0
Memory               0
Gpu                  0
OpSys               53
Weight              22
Price_euros          0
dtype: int64

In [ ]:



import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(20,10), dpi= 80)
sns.heatmap(train.corr(), xticklabels=train.corr().columns, yticklabels=train.corr().columns, cmap='RdYlGn', center=0, annot=True)


plt.title('Матрица корреляции', fontsize=30)
plt.xticks(fontsize=10)
plt.yticks(fontsize=10)
plt.show()