# Вариант 1.

Кто делает:
1. Александров Данила Александрович
2. Быков Дмитрий Александрович 
3. Горбунов Сергей Михайлович 
4. Горячко Дарья Романовна 
5. Громов Алексей Игоревич
6. Ивлиев Степан Дмитриевич

**Задача 1.**

**1-я входная строка** - год (опционально месяц и день) в формате ISO начала отсчёта.

**2-я входная строка** - год (опционально месяц и день) в формате ISO окончания отсчёта.

Создайте функцию, которая принимает на вход два введенных года и возвращает список (numpy array) дат с шагом в 1 день от начала до окончания отсчёта (последний день не включается).

Результат должен представлять из себя список дат в формате ISO.
Пример - 2005-02-25, где

- 2005 - год
- 02 - месяц
- 25 - день

In [8]:
# ваше решение
import numpy as np


def beauty_output(num):
  return num if num >= 10 else '0' + str(num)
  

def dates(year1, year2):
  res = []
  month = 0
  for year in range(year1, year2):
    for month in range(1, 12 + 1):
      for date in range(1, 31 + 1):
        res.append(f"{year}-{ beauty_output(month) }-{ beauty_output(date) }")
  return res


year1 = int(input())
year2 = int(input())

dates(year1, year2)

2001
2003

['2001-01-01',
 '2001-01-02',
 '2001-01-03',
 '2001-01-04',
 '2001-01-05',
 '2001-01-06',
 '2001-01-07',
 '2001-01-08',
 '2001-01-09',
 '2001-01-10',
 '2001-01-11',
 '2001-01-12',
 '2001-01-13',
 '2001-01-14',
 '2001-01-15',
 '2001-01-16',
 '2001-01-17',
 '2001-01-18',
 '2001-01-19',
 '2001-01-20',
 '2001-01-21',
 '2001-01-22',
 '2001-01-23',
 '2001-01-24',
 '2001-01-25',
 '2001-01-26',
 '2001-01-27',
 '2001-01-28',
 '2001-01-29',
 '2001-01-30',
 '2001-01-31',
 '2001-02-01',
 '2001-02-02',
 '2001-02-03',
 '2001-02-04',
 '2001-02-05',
 '2001-02-06',
 '2001-02-07',
 '2001-02-08',
 '2001-02-09',
 '2001-02-10',
 '2001-02-11',
 '2001-02-12',
 '2001-02-13',
 '2001-02-14',
 '2001-02-15',
 '2001-02-16',
 '2001-02-17',
 '2001-02-18',
 '2001-02-19',
 '2001-02-20',
 '2001-02-21',
 '2001-02-22',
 '2001-02-23',
 '2001-02-24',
 '2001-02-25',
 '2001-02-26',
 '2001-02-27',
 '2001-02-28',
 '2001-02-29',
 '2001-02-30',
 '2001-02-31',
 '2001-03-01',
 '2001-03-02',
 '2001-03-03',
 '2001-03-04',
 '2001-03-05',
 '2001-03-06',
 '2001-03-07',
 '2001-03-08',
 '2001-03-09',
 '2001-03-10',
 '2001-03-11',
 '2001-03-12',
 '2001-03-13',
 '2001-03-14',
 '2001-03-15',
 '2001-03-16',
 '2001-03-17',
 '2001-03-18',
 '2001-03-19',
 '2001-03-20',
 '2001-03-21',
 '2001-03-22',
 '2001-03-23',
 '2001-03-24',
 '2001-03-25',
 '2001-03-26',
 '2001-03-27',
 '2001-03-28',
 '2001-03-29',
 '2001-03-30',
 '2001-03-31',
 '2001-04-01',
 '2001-04-02',
 '2001-04-03',
 '2001-04-04',
 '2001-04-05',
 '2001-04-06',
 '2001-04-07',
 '2001-04-08',
 '2001-04-09',
 '2001-04-10',
 '2001-04-11',
 '2001-04-12',
 '2001-04-13',
 '2001-04-14',
 '2001-04-15',
 '2001-04-16',
 '2001-04-17',
 '2001-04-18',
 '2001-04-19',
 '2001-04-20',
 '2001-04-21',
 '2001-04-22',
 '2001-04-23',
 '2001-04-24',
 '2001-04-25',
 '2001-04-26',
 '2001-04-27',
 '2001-04-28',
 '2001-04-29',
 '2001-04-30',
 '2001-04-31',
 '2001-05-01',
 '2001-05-02',
 '2001-05-03',
 '2001-05-04',
 '2001-05-05',
 '2001-05-06',
 '2001-05-07',
 '2001-05-08',
 '2001-05-09',
 '2001-05-10',
 '2001-05-11',
 '2001-05-12',
 '2001-05-13',
 '2001-05-14',
 '2001-05-15',
 '2001-05-16',
 '2001-05-17',
 '2001-05-18',
 '2001-05-19',
 '2001-05-20',
 '2001-05-21',
 '2001-05-22',
 '2001-05-23',
 '2001-05-24',
 '2001-05-25',
 '2001-05-26',
 '2001-05-27',
 '2001-05-28',
 '2001-05-29',
 '2001-05-30',
 '2001-05-31',
 '2001-06-01',
 '2001-06-02',
 '2001-06-03',
 '2001-06-04',
 '2001-06-05',
 '2001-06-06',
 '2001-06-07',
 '2001-06-08',
 '2001-06-09',
 '2001-06-10',
 '2001-06-11',
 '2001-06-12',
 '2001-06-13',
 '2001-06-14',
 '2001-06-15',
 '2001-06-16',
 '2001-06-17',
 '2001-06-18',
 '2001-06-19',
 '2001-06-20',
 '2001-06-21',
 '2001-06-22',
 '2001-06-23',
 '2001-06-24',
 '2001-06-25',
 '2001-06-26',
 '2001-06-27',
 '2001-06-28',
 '2001-06-29',
 '2001-06-30',
 '2001-06-31',
 '2001-07-01',
 '2001-07-02',
 '2001-07-03',
 '2001-07-04',
 '2001-07-05',
 '2001-07-06',
 '2001-07-07',
 '2001-07-08',
 '2001-07-09',
 '2001-07-10',
 '2001-07-11',
 '2001-07-12',
 '2001-07-13',
 '2001-07-14',
 '2001-07-15',
 '2001-07-16',
 '2001-07-17',
 '2001-07-18',
 '2001-07-19',
 '2001-07-20',
 '2001-07-21',
 '2001-07-22',
 '2001-07-23',
 '2001-07-24',
 '2001-07-25',
 '2001-07-26',
 '2001-07-27',
 '2001-07-28',
 '2001-07-29',
 '2001-07-30',
 '2001-07-31',
 '2001-08-01',
 '2001-08-02',
 '2001-08-03',
 '2001-08-04',
 '2001-08-05',
 '2001-08-06',
 '2001-08-07',
 '2001-08-08',
 '2001-08-09',
 '2001-08-10',
 '2001-08-11',
 '2001-08-12',
 '2001-08-13',
 '2001-08-14',
 '2001-08-15',
 '2001-08-16',
 '2001-08-17',
 '2001-08-18',
 '2001-08-19',
 '2001-08-20',
 '2001-08-21',
 '2001-08-22',
 '2001-08-23',
 '2001-08-24',
 '2001-08-25',
 '2001-08-26',
 '2001-08-27',
 '2001-08-28',
 '2001-08-29',
 '2001-08-30',
 '2001-08-31',
 '2001-09-01',
 '2001-09-02',
 '2001-09-03',
 '2001-09-04',
 '2001-09-05',
 '2001-09-06',
 '2001-09-07',
 '2001-09-08',
 '2001-09-09',
 '2001-09-10',
 '2001-09-11',
 '2001-09-12',
 '2001-09-13',
 '2001-09-14',
 '2001-09-15',
 '2001-09-16',
 '2001-09-17',
 '2001-09-18',
 '2001-09-19',
 '2001-09-20',
 '2001-09-21',
 '2001-09-22',
 '2001-09-23',
 '2001-09-24',
 '2001-09-25',
 '2001-09-26',
 '2001-09-27',
 '2001-09-28',
 '2001-09-29',
 '2001-09-30',
 '2001-09-31',
 '2001-10-01',
 '2001-10-02',
 '2001-10-03',
 '2001-10-04',
 '2001-10-05',
 '2001-10-06',
 '2001-10-07',
 '2001-10-08',
 '2001-10-09',
 '2001-10-10',
 '2001-10-11',
 '2001-10-12',
 '2001-10-13',
 '2001-10-14',
 '2001-10-15',
 '2001-10-16',
 '2001-10-17',
 '2001-10-18',
 '2001-10-19',
 '2001-10-20',
 '2001-10-21',
 '2001-10-22',
 '2001-10-23',
 '2001-10-24',
 '2001-10-25',
 '2001-10-26',
 '2001-10-27',
 '2001-10-28',
 '2001-10-29',
 '2001-10-30',
 '2001-10-31',
 '2001-11-01',
 '2001-11-02',
 '2001-11-03',
 '2001-11-04',
 '2001-11-05',
 '2001-11-06',
 '2001-11-07',
 '2001-11-08',
 '2001-11-09',
 '2001-11-10',
 '2001-11-11',
 '2001-11-12',
 '2001-11-13',
 '2001-11-14',
 '2001-11-15',
 '2001-11-16',
 '2001-11-17',
 '2001-11-18',
 '2001-11-19',
 '2001-11-20',
 '2001-11-21',
 '2001-11-22',
 '2001-11-23',
 '2001-11-24',
 '2001-11-25',
 '2001-11-26',
 '2001-11-27',
 '2001-11-28',
 '2001-11-29',
 '2001-11-30',
 '2001-11-31',
 '2001-12-01',
 '2001-12-02',
 '2001-12-03',
 '2001-12-04',
 '2001-12-05',
 '2001-12-06',
 '2001-12-07',
 '2001-12-08',
 '2001-12-09',
 '2001-12-10',
 '2001-12-11',
 '2001-12-12',
 '2001-12-13',
 '2001-12-14',
 '2001-12-15',
 '2001-12-16',
 '2001-12-17',
 '2001-12-18',
 '2001-12-19',
 '2001-12-20',
 '2001-12-21',
 '2001-12-22',
 '2001-12-23',
 '2001-12-24',
 '2001-12-25',
 '2001-12-26',
 '2001-12-27',
 '2001-12-28',
 '2001-12-29',
 '2001-12-30',
 '2001-12-31',
 '2002-01-01',
 '2002-01-02',
 '2002-01-03',
 '2002-01-04',
 '2002-01-05',
 '2002-01-06',
 '2002-01-07',
 '2002-01-08',
 '2002-01-09',
 '2002-01-10',
 '2002-01-11',
 '2002-01-12',
 '2002-01-13',
 '2002-01-14',
 '2002-01-15',
 '2002-01-16',
 '2002-01-17',
 '2002-01-18',
 '2002-01-19',
 '2002-01-20',
 '2002-01-21',
 '2002-01-22',
 '2002-01-23',
 '2002-01-24',
 '2002-01-25',
 '2002-01-26',
 '2002-01-27',
 '2002-01-28',
 '2002-01-29',
 '2002-01-30',
 '2002-01-31',
 '2002-02-01',
 '2002-02-02',
 '2002-02-03',
 '2002-02-04',
 '2002-02-05',
 '2002-02-06',
 '2002-02-07',
 '2002-02-08',
 '2002-02-09',
 '2002-02-10',
 '2002-02-11',
 '2002-02-12',
 '2002-02-13',
 '2002-02-14',
 '2002-02-15',
 '2002-02-16',
 '2002-02-17',
 '2002-02-18',
 '2002-02-19',
 '2002-02-20',
 '2002-02-21',
 '2002-02-22',
 '2002-02-23',
 '2002-02-24',
 '2002-02-25',
 '2002-02-26',
 '2002-02-27',
 '2002-02-28',
 '2002-02-29',
 '2002-02-30',
 '2002-02-31',
 '2002-03-01',
 '2002-03-02',
 '2002-03-03',
 '2002-03-04',
 '2002-03-05',
 '2002-03-06',
 '2002-03-07',
 '2002-03-08',
 '2002-03-09',
 '2002-03-10',
 '2002-03-11',
 '2002-03-12',
 '2002-03-13',
 '2002-03-14',
 '2002-03-15',
 '2002-03-16',
 '2002-03-17',
 '2002-03-18',
 '2002-03-19',
 '2002-03-20',
 '2002-03-21',
 '2002-03-22',
 '2002-03-23',
 '2002-03-24',
 '2002-03-25',
 '2002-03-26',
 '2002-03-27',
 '2002-03-28',
 '2002-03-29',
 '2002-03-30',
 '2002-03-31',
 '2002-04-01',
 '2002-04-02',
 '2002-04-03',
 '2002-04-04',
 '2002-04-05',
 '2002-04-06',
 '2002-04-07',
 '2002-04-08',
 '2002-04-09',
 '2002-04-10',
 '2002-04-11',
 '2002-04-12',
 '2002-04-13',
 '2002-04-14',
 '2002-04-15',
 '2002-04-16',
 '2002-04-17',
 '2002-04-18',
 '2002-04-19',
 '2002-04-20',
 '2002-04-21',
 '2002-04-22',
 '2002-04-23',
 '2002-04-24',
 '2002-04-25',
 '2002-04-26',
 '2002-04-27',
 '2002-04-28',
 '2002-04-29',
 '2002-04-30',
 '2002-04-31',
 '2002-05-01',
 '2002-05-02',
 '2002-05-03',
 '2002-05-04',
 '2002-05-05',
 '2002-05-06',
 '2002-05-07',
 '2002-05-08',
 '2002-05-09',
 '2002-05-10',
 '2002-05-11',
 '2002-05-12',
 '2002-05-13',
 '2002-05-14',
 '2002-05-15',
 '2002-05-16',
 '2002-05-17',
 '2002-05-18',
 '2002-05-19',
 '2002-05-20',
 '2002-05-21',
 '2002-05-22',
 '2002-05-23',
 '2002-05-24',
 '2002-05-25',
 '2002-05-26',
 '2002-05-27',
 '2002-05-28',
 '2002-05-29',
 '2002-05-30',
 '2002-05-31',
 '2002-06-01',
 '2002-06-02',
 '2002-06-03',
 '2002-06-04',
 '2002-06-05',
 '2002-06-06',
 '2002-06-07',
 '2002-06-08',
 '2002-06-09',
 '2002-06-10',
 '2002-06-11',
 '2002-06-12',
 '2002-06-13',
 '2002-06-14',
 '2002-06-15',
 '2002-06-16',
 '2002-06-17',
 '2002-06-18',
 '2002-06-19',
 '2002-06-20',
 '2002-06-21',
 '2002-06-22',
 '2002-06-23',
 '2002-06-24',
 '2002-06-25',
 '2002-06-26',
 '2002-06-27',
 '2002-06-28',
 '2002-06-29',
 '2002-06-30',
 '2002-06-31',
 '2002-07-01',
 '2002-07-02',
 '2002-07-03',
 '2002-07-04',
 '2002-07-05',
 '2002-07-06',
 '2002-07-07',
 '2002-07-08',
 '2002-07-09',
 '2002-07-10',
 '2002-07-11',
 '2002-07-12',
 '2002-07-13',
 '2002-07-14',
 '2002-07-15',
 '2002-07-16',
 '2002-07-17',
 '2002-07-18',
 '2002-07-19',
 '2002-07-20',
 '2002-07-21',
 '2002-07-22',
 '2002-07-23',
 '2002-07-24',
 '2002-07-25',
 '2002-07-26',
 '2002-07-27',
 '2002-07-28',
 '2002-07-29',
 '2002-07-30',
 '2002-07-31',
 '2002-08-01',
 '2002-08-02',
 '2002-08-03',
 '2002-08-04',
 '2002-08-05',
 '2002-08-06',
 '2002-08-07',
 '2002-08-08',
 '2002-08-09',
 '2002-08-10',
 '2002-08-11',
 '2002-08-12',
 '2002-08-13',
 '2002-08-14',
 '2002-08-15',
 '2002-08-16',
 '2002-08-17',
 '2002-08-18',
 '2002-08-19',
 '2002-08-20',
 '2002-08-21',
 '2002-08-22',
 '2002-08-23',
 '2002-08-24',
 '2002-08-25',
 '2002-08-26',
 '2002-08-27',
 '2002-08-28',
 '2002-08-29',
 '2002-08-30',
 '2002-08-31',
 '2002-09-01',
 '2002-09-02',
 '2002-09-03',
 '2002-09-04',
 '2002-09-05',
 '2002-09-06',
 '2002-09-07',
 '2002-09-08',
 '2002-09-09',
 '2002-09-10',
 '2002-09-11',
 '2002-09-12',
 '2002-09-13',
 '2002-09-14',
 '2002-09-15',
 '2002-09-16',
 '2002-09-17',
 '2002-09-18',
 '2002-09-19',
 '2002-09-20',
 '2002-09-21',
 '2002-09-22',
 '2002-09-23',
 '2002-09-24',
 '2002-09-25',
 '2002-09-26',
 '2002-09-27',
 '2002-09-28',
 '2002-09-29',
 '2002-09-30',
 '2002-09-31',
 '2002-10-01',
 '2002-10-02',
 '2002-10-03',
 '2002-10-04',
 '2002-10-05',
 '2002-10-06',
 '2002-10-07',
 '2002-10-08',
 '2002-10-09',
 '2002-10-10',
 '2002-10-11',
 '2002-10-12',
 '2002-10-13',
 '2002-10-14',
 '2002-10-15',
 '2002-10-16',
 '2002-10-17',
 '2002-10-18',
 '2002-10-19',
 '2002-10-20',
 '2002-10-21',
 '2002-10-22',
 '2002-10-23',
 '2002-10-24',
 '2002-10-25',
 '2002-10-26',
 '2002-10-27',
 '2002-10-28',
 '2002-10-29',
 '2002-10-30',
 '2002-10-31',
 '2002-11-01',
 '2002-11-02',
 '2002-11-03',
 '2002-11-04',
 '2002-11-05',
 '2002-11-06',
 '2002-11-07',
 '2002-11-08',
 '2002-11-09',
 '2002-11-10',
 '2002-11-11',
 '2002-11-12',
 '2002-11-13',
 '2002-11-14',
 '2002-11-15',
 '2002-11-16',
 '2002-11-17',
 '2002-11-18',
 '2002-11-19',
 '2002-11-20',
 '2002-11-21',
 '2002-11-22',
 '2002-11-23',
 '2002-11-24',
 '2002-11-25',
 '2002-11-26',
 '2002-11-27',
 '2002-11-28',
 '2002-11-29',
 '2002-11-30',
 '2002-11-31',
 '2002-12-01',
 '2002-12-02',
 '2002-12-03',
 '2002-12-04',
 '2002-12-05',
 '2002-12-06',
 '2002-12-07',
 '2002-12-08',
 '2002-12-09',
 '2002-12-10',
 '2002-12-11',
 '2002-12-12',
 '2002-12-13',
 '2002-12-14',
 '2002-12-15',
 '2002-12-16',
 '2002-12-17',
 '2002-12-18',
 '2002-12-19',
 '2002-12-20',
 '2002-12-21',
 '2002-12-22',
 '2002-12-23',
 '2002-12-24',
 '2002-12-25',
 '2002-12-26',
 '2002-12-27',
 '2002-12-28',
 '2002-12-29',
 '2002-12-30',
 '2002-12-31']

**Задача 2.**

Используя numpy:

Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число el1), и разность (вещественное число d) и создает матрицу по диагонали, которой распологаются первые N членов арифметической прогрессии.

In [12]:
# ваше решение

n   = int(input())
el1 = float(input())
d   = float(input())

res = np.zeros((n, n))
for i in range(n):
  res[i, i] = el1 + d * i

res

10
1
0.1

array([[1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 1.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 1.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 1.3, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 1.4, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 1.5, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 1.6, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 1.7, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1.8, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1.9]])

**Задача 3.**

Дан массив. Создайте функцию, которая принимает данный массив и проверяет наличие пропусков и возвращает их количество:
- если есть пропуски, то функция должна их заполнить теми значениями, которые пользователь вводит с клавиатуры.
- если нет пропусков, то функция возвращает 0.

*Встроенные функции заполнения пропусков использовать запрещено.*

In [19]:
# ваше решение 


mass = np.array([np.nan, 1, np.nan, 2, np.nan, np.inf], float)


def task2():
  global mass

  res = 0
  for i in range(mass.shape[0]):
    if np.isnan(mass[i]) or np.isinf(mass[i]):
      mass[i] = replacement
      res += 1
  return res


replacement = float(input())
print(task2())
mass

-1
4

array([-1.,  1., -1.,  2., -1., -1.])

**Задача 4.**

Вам дан массив, содержащий категории некоторого объекта в виде строк.

Создайте функцию, которая принимает на вход массив, хранящий категории объектов и возвращает:
- закодированный список из чисел, где каждому числу соответсвует какая-то категория;
- число категорий;
- словарь кодирования;

**Например:**

Ввод:

`('red', 'green', 'red', 'blue')`

Вывод:
```(0, 1, 0, 2)
Количество категорий: 3
Словарь кодирования: 
{'red': 0, 'green': 1, 'blue': 2'}
```

*P.s. встроенными функциями кодирования пользоваться запрещено.*

In [42]:
# ваше решение


def my_split(line):
  res = []
  word = ''
  read_word = False
  for i in line:
    if i == "'":
      read_word = not read_word
      continue
    if read_word:
      word += i
    if not read_word and word != '':
      res.append(word)
      word = ''
  r1, r2, r3 = range(1, len(res) + 1, 1), 0, dict()
  for i in r1:
    r3[res[i - 1]] = 0
  for index, item in enumerate(r3.items()):
    r3[item[0]] = index 
  return r1, len(r3), r3


line = input()
r1, r2, r3 = my_split(line)
print(f"Количество категорий: {r2} \nСловарь кодирования: \n{r3}")

('red', 'green', 'red', 'blue')
Количество категорий: 3
Словарь кодирования:
{'red': 0, 'green': 1, 'blue': 2}

# Вариант 2.

Кто делает:
1. Игнатов Константин Дмитриевич
2. Казанов Амир Ринатович
3. Клячин Иван Николаевич
4. Котов Александр Андреевич
5. Мелешкин Кирилл Андреевич
6. Морозов Максим Олегович

**Задача 1.**

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Создайте функцию, которая принимает 3 введеных числа и возвращает список (numpy.array) из n точек на отрезке (start, stop), попарно равноудалённых друг от друга и от концов отрезка (т.е. разделите отрезок на n+1 часть). Округлите значения точек до 3 знака после запятой.

In [ ]:
# ваше решение

**Задача 2.**

Дан массив размерностью NxM.

Напишите функцию, которая нормализует все элементы матрицы.

**Немного теории.** *Нормализацией данных называется приведение их к некоторой общей шкале без потери информации о различии диапазонов.*

*Новые значения элементов расчитываются как:*

$x' = \frac{x-x_{min}}{x_{max}-x_{min}}$

In [ ]:
# ваше решение

**Задача 3.**

Вам дан одномерный массив. Напишите функцию, которая принимает этот массив и возвращает:
1. Количество локальных максимумов для этого массива;
2. И сами эти максимумы.

*P.s. встроенными функциями пользоваться запрещено.*

In [ ]:
# ваше решение

**Задача 4.**

Реализуйте функцию умножения двух матриц, без использования встроенной функции.

In [ ]:
# ваше решение

# Вариант 3.

Кто делает:

1. Переттруов Никита Артемович
2. Пославский Егор Константинович
3. Садохин Константин Павлович
4. Скиданов Дмитрий Артёмович
5. Судариков Андрей Геннадьевич
6. Таланов Максим Андреевич

**Задача 1.**

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Создайте функцию, которая возвращает список из n точек на отрезке [start, stop] в геометрической прогрессии, включая start и stop.

Округлите значения точек до 3 знака после запятой.

In [ ]:
# ваше решение

**Задача 2.**

Дана матрица. Напишите функцию, которая принимает в качестве аргумента данную матрицу и возврщает транспонированную матрицу.

**Немного теории**. *Транспонированной матрицей $A^T$ называется матрица, полученная из исходной матрицы $A$ заменой строк на столбцы. Формально: элементы матрицы $A^T$ определяются как ${a^T}_{ij} = a_{ji}$, где ${a^T}_{ij}$ — элемент матрицы $A^T$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.*

P.s. использовать встроенные функции Numpy для транспонирования запрещено.

In [ ]:
# ваше решение

**Задача 3.**

Даны два массива A и B формы (8,3) и (2,2). 
Напишите фукнкцию, которая возвращает строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B?

In [ ]:
# ваше решение

**Задача 4.**

Дан вектор. Реализуйте функцию, которая возвращает каждый элемент в двоичном предствалении в виде вектора.

Например:

Ввод:

`[0, 1, 2, 3, 15, 16, 32, 64, 128]`

Вывод:

```
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
 ```

In [ ]:
# ваше решение

# Вариант 4.

Кто делает:
1. Игнатов Игорь Дмитриевич
2. Файзуллин Илья Денисович
3. Чупрова Ася Александровна
4. Ямпольская Ирина Вадимовна
5. Дидковский Илья Радионович

**Задача 1.**

Реализовать функцию, которая принимает матрицу 3x3 и возвращает обратную по отношеную к ней матрицу.

**Немного теории**. *Матрица $А^{-1}$ называется обратной матрицей по отношению к матрице $А$, если $А*А^{-1} = Е$, где $Е$ — единичная матрица n-го порядка. Обратная матрица может существовать только для квадратных матриц.*

P.s. использовать встроенные функции запрещено.

In [ ]:
# ваше решение

**Задача 2.**

Дан одномернный массив. Создайте функцию, которая принимает данные массив и возвращает массив, состоящий из элементов, целая часть от деления которых больше 3.

In [ ]:
# ваше решение

**Задача 3.**

Дана матрица 4х3 (содержащаяя координаты 4х векторов, столбцы это соотсветсвенно x,y,z) и вектор (x,y,z). Напишите функцию которая возвращает ближащий вектор из матрицы к заданому вектору (согласно расстоянию между векторами).

In [ ]:
# ваше решение

**Задача 4.**

Дан вектор из ненулевых элементов. Вставьте между каждыми элементами по три 0.

In [ ]:
# ваше решение